version: '3.8'
services:

  # Environment
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: afisha
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin


